"""Add missing user profile columns

Revision ID: 7eb30f0e4d5d
Revises: 
Create Date: 2025-08-09 19:38:10.282583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb30f0e4d5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mobile_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.String(length=32), nullable=True))
        batch_op.drop_column('theme_preference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_preference', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('employee_id')
        batch_op.drop_column('job_title')
        batch_op.drop_column('department')
        batch_op.drop_column('gender')
        batch_op.drop_column('postal_code')
        batch_op.drop_column('address')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('timezone')
        batch_op.drop_column('country')
        batch_op.drop_column('mobile_number')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
